# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 7, 13, 29, 857082, tzinfo=utc)),
        ),
    ]
