# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 04:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171103_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 5, 4, 50, 4, 66287, tzinfo=utc)),
        ),
    ]
